### PR TITLE
Standardize on arrow functions

### PR DESCRIPTION
**Pull request by andreban**
Switched to use arrow functions on callbacks.

### CODE REVIEW

**Comment by andreban** [comment]
@ithinkihaveacat PTAL

**Comment by ithinkihaveacat** [comment]
Can't figure out how to update this PR. If you add `"prefer-arrow-callback": 1` to `.eslintrc.json` eslint'll find a few more.

**Comment by andreban** [comment]
@ithinkihaveacat  Added the eslint config and fixed remaining arrow functions. PTAL.

**Comment by ithinkihaveacat** [comment]
LGTM

**Pull request merged**
