### PR TITLE
Adds entity-counts to Gulliver

### PR DESCRIPTION
**Pull request by andreban**
Entity counts are added using a transaction and an entity with a
special key `entity-count` in the entity.

### CODE REVIEW

**Comment by andreban** [comment]
Test deployed here: https://gulliver-1371.appspot.com/

**Comment by juliantoledo** [comment]
@andreban It's looking good, you could use similar CSS to ".pwabox-right .name" to make it match the PWSs titles or the buttons text size and weight.

**Comment by andreban** [comment]
@juliantoledo Updated the style. Deployed on the same server.

**Comment by juliantoledo** [comment]
@andreban I haven't been able to test it because the error I mentioned over chat. I will try again later.

**Comment by andreban** [comment]
@juliantoledo I found the problem. Can you test again?

**Comment by juliantoledo** [comment]
LGTM

**Comment by andreban** [comment]
@juliantoledo I've squashed the commits. Let's chat before merging / deploying so we can manually set the count for existing apps.

**Comment by juliantoledo** [comment]
tested, deployed and count updated.

**Pull request merged**
