### PR TITLE
Add Manifest to view.hbs

### PR DESCRIPTION
**Pull request by andreban**
Result looks like this:

screen shot 2016-09-07 at 1 55 15 pm

### CODE REVIEW

**Comment by juliantoledo** [comment]
@andreban I actually think we should show it in some kind of lightbox, maybe using pure CSS and having a raw link to the actual manifest.

**Comment by juliantoledo** [comment]
What do you think about the lightbox or even make it css expandable? Do you prefer to do it in another PR?

**Comment by andreban** [comment]
I think we can go with expanding? I'd rather do in another PR.

**Comment by juliantoledo** [comment]
LGTM

**Pull request merged**
