### PR TITLE
Refactor PWA Object

### PR DESCRIPTION
**Pull request by andreban**
- Eliminate the 'mergeManifest' method
- The fields that were being copied by that method are now get fields on the manifest.

### CODE REVIEW

**Comment by andreban** [comment]
Improves #80

**Comment by andreban** [comment]
staged here: https://gulliver-1371.appspot.com/

**Comment by juliantoledo** [comment]
It's crashing when I load the page:
App listening on port 8080
/Users/jtoledo/GitHub/gulliver/node_modules/express/lib/router/index.js:618
    return fn.apply(this, arguments);
             ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/jtoledo/GitHub/gulliver/node_modules/express/lib/router/index.js:618:14
    at Immediate.next (/Users/jtoledo/GitHub/gulliver/node_modules/express/lib/router/index.js:256:14)
    at Immediate.<anonymous> (/Users/jtoledo/GitHub/gulliver/node_modules/express/lib/router/index.js:618:15)
    at Immediate.immediate._onImmediate (timers.js:585:18)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

**Comment by andreban** [comment]
Can you try with and empty DB? My changes probably change the format of the PWA object.

**Comment by juliantoledo** [comment]
LGTM

**Pull request merged**
