### PR TITLE
Fix Pagination code

### PR DESCRIPTION
**Pull request by andreban**
Fixes the existing pagination.

Related to #72

### CODE REVIEW

**Comment by juliantoledo** [comment]
How can I test it?

**Comment by andreban** [comment]
@juliantoledo add more than 10 PWA's to your instance or change the `LIST_PAGE_SIZE`on `crud.js` to a small number (I've been testing with `1`).

**Comment by juliantoledo** [comment]
@andreban Yes, I was able to test it now. How do you go back? should we have another link?

**Comment by andreban** [comment]
Check my comment on #72 

The preferred way to handle pagination in cloud-datastore is using the cursor pointer, since using offset/limit scales linearly. 

The issue is that I don't get a pointer to the previous page, only the next. We could store this in the session or something but it would still break if someone sends the link to other person.

**Comment by juliantoledo** [comment]
We should take a deeper look before adding this then.

**Comment by juliantoledo** [comment]
@andreban would it be possible to keep the pointer to previews page as URL parameter?

**Comment by andreban** [comment]
Closing this as we're going back to the skip/limit solution.

**Pull request closed without merging**
