### PR TITLE
Add simple service worker and sw-toolbox

### PR DESCRIPTION
**Pull request by ithinkihaveacat**
Part of #69.

### CODE REVIEW

**Comment by andreban** [comment]
Are we considering using `sw-precache` for the static content? If so, we might want to add a build process (eg: gulp)?

**Comment by ithinkihaveacat** [comment]
@andreban I did look at `sw-precache` but I think `sw-toolbox` gives slightly better control. And I was hoping that for now we could hand-write the configuration. (Might change my mind after doing a bit more work though.)

And I think we will need a build tool at some point, but hope to get away without it for now.

**Comment by juliantoledo** [comment]
+1 one on gulp, but also +1 on doing it later. I will take a deeper look tomorrow.

**Comment by juliantoledo** [comment]
LGTM

**Pull request merged**
