### PR TITLE
Add memcached to Gulliver

### PR DESCRIPTION
**Pull request by andreban**
- Adds cache when listing pwas
- Adds cache when retrieving a single PWA

### CODE REVIEW

**Comment by juliantoledo** [comment]
From chat:
- [ ] Skip memcache if not avaiable
- [ ] Add memcache local installation to readme

**Comment by andreban** [comment]
- Tweaked timeout to fail faster. This will print a message to console letting the developer know that memcached is not installed.
- Added instructions to Readme.
- Failure already worked, but was taking too long due to long timeouts / retries.

**Comment by andreban** [comment]
PTAL

**Comment by juliantoledo** [comment]
LGTM

**Pull request merged**
